#!/usr/bin/env python3
"""Build slate-topo.html — the whole app in one self-contained file.

Inlines css/style.css and every <script src> (opentype.js, embedded fonts,
app code) into index.html so the result runs from anywhere: double-clicked
from Downloads, emailed, dropped on a USB stick. Regenerate after editing
any source file:

    python3 tools/build-single-file.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "slate-topo.html"

html = (ROOT / "index.html").read_text()

def inline_css(m: re.Match) -> str:
    css = (ROOT / m.group(1)).read_text()
    assert "</style" not in css.lower()
    return "<style>\n" + css + "</style>"

def inline_js(m: re.Match) -> str:
    js = (ROOT / m.group(1)).read_text()
    assert "</script" not in js.lower(), m.group(1)
    return "<script>\n" + js + "\n</script>"

html, n_css = re.subn(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)
html, n_js = re.subn(r'<script src="([^"]+)"></script>', inline_js, html)
assert n_css == 1, n_css
assert n_js == 5, n_js

banner = ("<!-- Generated by tools/build-single-file.py — do not edit directly; "
          "edit index.html / css/ / js/ and rebuild. -->\n")
html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

OUT.write_text(html)
print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB, inlined {n_css} css + {n_js} js)")
